# Training configuration
TRAINING_SPLIT = 1
LEARNING_RATE = 1e-7
MOMENTUM = 0.9
HARD_NEGATIVE_RATIO = 3
BATCH_SIZE = 1
TRAINING_ITERATIONS = 4
EPOCHS = 1
VALIDATION_SPLIT = 0.2

# Saving configuration
SAVE_FOLDER_PATH = "save_folder"
SAVING_FREQUENCY = int(TRAINING_ITERATIONS / 4)
